version: "3.1"
services:
    db:
      image: mariadb
      container_name: mariadb
      working_dir: /app
      volumes:
        - .database/mysql:/app
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /app
      volumes:
          - .:/app
          - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./config/nginx/logs/:/var/log/nginx
      ports:
       - "80:80"

    php-fpm:
      build: config/php-fpm
      container_name: php-fpm
      working_dir: /app
      volumes:
        - .:/app
        - ./config/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/php.ini
        - ./config/php-fpm/xdebug-ini-overrides.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
